config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'admin/home', as: :admin
  get 'admin' => 'admin#home'

  get 'pages/about', as: :about
  get 'pages/contact', as: :contact

  resources :portfolios
  resources :categories do
    resources :products
  end

  devise_for :admins

  post 'quote', to: 'quotes#create', as: 'quote_request'
  post 'contact', to: 'contacts#create', as: 'contact_request'

end

app/views/pages/contact.html.erb
<!-- google -->
<div class="maps location-map visible-md visible-lg">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3589.9153865752673!2d-80.21130398518845!3d25.872262110330244!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d9b195781dd15b%3A0x76f164762f0bfba3!2sHappy+Endings+Custom+Printed+Shirts+%26+Promotional+Items!5e0!3m2!1sen!2sus!4v1453966759464" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
<div class="form-group form-wrapper text-center">
  <h4>Get In Touch!</h4>
  <%= form_for @contact, url: contact_request_path do |f| %>
    <%= f.text_field :name, placeholder:"Name",class: "form-control" %><br><br>
    <%= f.text_field :email, placeholder:"Email",class: "form-control" %><br><br>
    <%= f.text_field :phone, placeholder:"Phone",class: "form-control" %><br><br>
    <%= f.text_area :comments, placeholder:"Comments",class: "form-control" %><br><br>
    <%= f.submit "Submit", class: "btn btn-basecamp" %>
  <% end %>
</div>
<div class="cta text-center">
  <h5>
    Get in touch with us.<br>
    we get back to all inquiries promptly.

  </h5>
    <div class="heading-info text-center">
      <i class="fa fa-clock fa-5x"></i>&nbsp;<h3>Hours of Operation: Monday - Friday <br> 9am - 6pm</h3><br>
      <i class="fa fa-phone fa-5x"></i>&nbsp;<h3>Phone: 305-759-4467</h3><br>
      <i class="fa fa-fax fa-5x"></i>&nbsp;<h3>Fax: 305-751-0220</h3><br>
        <a href="tel:+13057594467" class="btn btn-basecamp">Call Us!</a>
    </div>
</div>
<br>

app/views/pages/home.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 elCarousel">
     <div id="carousel-example-generic" class="carousel slide slides carousel-border" data-ride="carousel">
       <!-- Indicators -->
       <ol class="carousel-indicators">
         <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
         <li data-target="#carousel-example-generic" data-slide-to="1"></li>
         <li data-target="#carousel-example-generic" data-slide-to="2"></li>
       </ol>
       <!-- Wrapper for slides -->
       <div class="carousel-inner" role="listbox">
         <div class="item active">
           <img src="1slide.jpg" alt="Chania">
         </div>

         <div class="item">
           <img src="2slide.jpg" alt="Chania">
         </div>

         <div class="item">
           <img src="3slide.jpg" alt="Flower">
         </div>
       </div>
       <!-- Controls -->
       <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
         <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
         <span class="sr-only">Previous</span>
       </a>
       <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
         <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
         <span class="sr-only">Next</span>
       </a>
    </div>
   </div>
  <div class="col-sm-12 col-md-4 text-center">
    <h3>Get A Quote</h3>
    <div class="form-group">
      <%= form_for @quote, url: quote_request_path do |f| %>
        <%= f.text_field :name, placeholder:"Name",class: "form-control" %><br>
        <%= f.text_field :email, placeholder:"Email",class: "form-control" %><br>
        <%= f.text_field :phone, placeholder:"Phone",class: "form-control" %><br>
        <%= f.text_field :item, placeholder:"Item",class: "form-control" %><br>
        <%= f.text_area :comments, placeholder:"Print Description",class: "form-control" %><br>
        <%= f.submit "Submit", class: "btn btn-basecamp" %>
      <% end %>
    </div>
  </div>
</div>

<div class="why_us padding text-center">
  <h2>Take advantage of our Easy Ordering Process</h2>
  <hr>
  <div class="row">
    <div class="col-sm-12 col-md-4 pad-btm">
      <img  class="img-responsive img-margin" src="http://i.imgur.com/lYpWxyV.png" alt="shirts" />
      <p>
        <h4>It all Starts with art!</h4>
        <p>Email us your design, or we can create one for you.</p>
      </p>
    </div>
    <div class="col-sm-12 col-md-4 pad-btm">
      <img class="img-responsive center-block" src="http://i.imgur.com/AcDMOfS.png" alt="shirts" />
      <p>
        <h4>Pick your Promotional Product!</h4>
        <p>Browse our inventory as well as our extensive catalogs.</p>
      </p>
    </div>
    <div class="col-sm-12 col-md-4 pad-btm">
      <img  class="img-responsive img-margin" src="http://i.imgur.com/ozGgSNS.png" alt="shirts" />
      <p>
        <h4>Submit for a fast quote!</h4>
        <p>Once approved we turn around our orders quickly.</p>
      </p>
    </div>
  </div>
  <hr>
  <div class="row">
    <% if browser.mobile? %>
      <div class="col-xs-12">
        <h2>Established in 1976</h2>
      </div>
      <div class="col-xs-6">
        <img  class="img-responsive" style="max-height: 4em;margin: 0 auto;" src="https://i.imgur.com/FYM7HcQ.png" alt="smiley" />
      </div>
      <div class="col-xs-6">
        <img  class="img-responsive" style="max-height: 4em;margin: 0 auto;" src="https://i.imgur.com/gXc25Rk.png" alt="logo2" />
      </div>
    <% else %>
      <div class="col-xs-4">
        <img  class="img-responsive" style="max-height: 4em;margin: 0 auto;" src="https://i.imgur.com/FYM7HcQ.png" alt="smiley" />
      </div>
      <div class="col-xs-4">
        <h2>Established in 1976</h2>
      </div>
      <div class="col-xs-4">
        <img  class="img-responsive" style="max-height: 4em;margin: 0 auto;" src="https://i.imgur.com/gXc25Rk.png" alt="logo2" />
      </div>
    <% end %>
  </div>
</div>
<!-- <div class="testimonials padding text-center">
  <h1>Testimonials</h1>
  <img  class="img-responsive img-margin" src="http://i.imgur.com/rRVRrpo.jpg" alt="shirts" />
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
    fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
    mollit anim id est laborum.
  </p>
</div> -->
<!-- Products -->
<!-- <div class="products padding text-center">
  <h1>Products</h1>
  <% if @products.present? %>
  <% if browser.mobile? %>
    <% @products.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.compact.each do |product| %>
              <div class="col-sm-12 col-md-4">
                <div class="tile-offset" style="background-image:url('<%= product.image_1 %>');">
                  <a href="<%= url_for([@category, product ]) %>">
                  <div class="product-overlay HIDE">
                    <div class="title">
                      <h3 style="padding-top: 50%;"><%= product.name %></h3>
                    </div>
                    <div class="bottom" style="background-image:url(http://i.imgur.com/6HsvJeM.png), url(http://i.imgur.com/IPQHutD.png);background-size:50%,51%;background-position:left,right;background-repeat:no-repeat;">
                      <div class="bottom-left">
                        <h6>AS LOW AS</h6>
                        <h4>$<%= product.price %></h4>
                      </div>
                      <div class="bottom-right">
                        <h6 style="left: 6px;">
                          <a style="color: white;" href="<%= url_for([@category, product ]) %>">
                          Quote
                        </a>
                      </h6>
                      </div>
                    </div>
                  </div>
                </a>
                </div>
                <% if admin_signed_in? %>
                  <%= link_to 'Show', [product.category, product], class: "btn btn-primary" %>&nbsp;
                  <%= link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-basecamp" %>&nbsp;
                  <%= link_to 'Destroy', [product.category, product], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                <% end %>
              </div>
        <% end %>
      </div>
    <% end %> -->
    <!-- end of mobile -->
    <!-- <% else %>
    <% @products.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.compact.each do |product| %>
              <div class="col-sm-12 col-md-4">
                <div class="tile-offset" style="background-image:url('<%= product.image_1 %>');">
                  <div class="product-overlay HIDE modaling" href="#exampleModal<%= product.id %>">
                    <div class="title">
                      <h3><%= product.name.titleize %></h3>
                    </div>
                    <div class="bottom" style="background-image:url(http://i.imgur.com/6HsvJeM.png), url(http://i.imgur.com/IPQHutD.png);background-size:50%,51%;background-position:left,right;background-repeat:no-repeat;">
                      <div class="bottom-left">
                        <h6>AS LOW AS</h6>
                        <h4>$<%= product.price %></h4>
                      </div>
                      <div class="bottom-right">
                        <h6>Quote</h6>
                      </div>
                    </div>
                  </div>
                </div>
                <% if admin_signed_in? %>
                  <%= link_to 'Show', [product.category, product], class: "btn btn-primary" %>&nbsp;
                  <%= link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-basecamp" %>&nbsp;
                  <%= link_to 'Destroy', [product.category, product], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                <% end %>
              </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% end %>
</div>

<% if @products.present? %>
  <% @products.each do |product| %>
    <div class="modal fade" id="exampleModal<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-center" id="exampleModalLabel<%= product.id %>"><%= product.name.titleize %></h4>
          </div>
          <div class="modal-body">
            <%= render product %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Send message</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %> -->
<!-- end of products -->




<!-- <div class="choose padding text-center">
  <h1>Why Choose us</h1>
  http://i.imgur.com/uL651d7.jpg
  <img  class="img-responsive img-rounded img-margin" src="http://i.imgur.com/mXEcK0w.jpg" alt="shirts" />
  <p>
    We are wholesale Custom Printers specializing in t-shirts, promotional products, and signs.
    Since 1976 Happy Endings has been providing superior printing and customer service.
  </p>
  <p>
    Our sales and manufacturing facilities are conveniently located on I-95 and 106th Street in Miami.
    We pride ourselves on being large enough to print mass quantities yet small enough to pay close
    attention to every customer.These qualities allow us to ensure everyone leaves with a happy ending.
  </p>
</div> -->