config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'admin/home', as: :admin
  get 'admin' => 'admin#home'

  get 'pages/about', as: :about
  get 'pages/contact', as: :contact

  resources :portfolios
  resources :categories do
    resources :products
  end

  devise_for :admins

  post 'quote', to: 'quotes#create', as: 'quote_request'
  post 'contact', to: 'contacts#create', as: 'contact_request'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy ]
  # before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_category, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = @category.products
    @quote = Quote.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = @category.products.find(params[:id])
    @quote = Quote.new
  end

  # GET /products/new
  def new
    @product = @category.products.build
  end

  # GET /products/1/edit
  def edit
    @product = @category.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = @category.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@product.category, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product = @category.products.find(params[:id])

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [@product.category, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = @category.products.find(params[:id])

    @product.destroy
    respond_to do |format|
      format.html { redirect_to category_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_category
      @category = Category.find(params[:category_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    # def set_product
    #   @product = @category.products.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category, :price, :image_1, :image_2, :promo)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for([@product.category, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_1 %><br>
    <%= f.text_field :image_1 %>
  </div>
  <div class="field">
    <%= f.label :image_2 %><br>
    <%= f.text_field :image_2 %>
  </div>
  <div class="field">
    <%= f.label :promo %><br>
    <%= f.check_box :promo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="text-center">
  <div class="row">
    <div class="col-sm-12 col-md-6 center-block">
      <h3 class="product-title"><%= product.name %></h3>
      <h4 class="aslow">
        As Low as &nbsp;
        <span class="low-price"><%= product.price %></span>
      </h4>
      <div class="col-sm-12">
        <%= image_tag(product.image_1, class: "img-responsive img-margin") %>
      </div>
      <div class="col-sm-12">
        <%= image_tag(product.image_2, class: "img-responsive img-margin") %>
      </div>
    </div>
    <div class="col-sm-12 col-md-6 center-block">
      <div class="form-group form-wrapper form-wrapper-show">
        <h4>Request a Quote</h4>
        <div class="form-group">
          <%= form_for @quote, url: quote_request_path do |f| %>
            <%= f.text_field :name, placeholder:"Name",class: "form-control" %><br><br>
            <%= f.text_field :email, placeholder:"Email",class: "form-control" %><br><br>
            <%= f.text_field :phone, placeholder:"Phone",class: "form-control" %><br><br>
            <%= f.text_field :item, value: "#{product.name}", class: "form-control" %><br><br>
            <%= f.text_area :comments, placeholder:"Comments",class: "form-control" %><br><br>
            <%= f.submit "Submit", class: "btn btn-basecamp" %>
          <% end %>
      </div>
    </div>
  </div>
  <% if admin_signed_in? %>
    <%= link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-basecamp" %> |
    <%= link_to 'Back', category_products_path(product.category), class: "btn btn-basecamp" %>
  <% end %>
</div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', [@product.category, @product] %> |
<%= link_to 'Back', category_products_path(@product.category) %>

app/views/products/index.html.erb
<div class="text-center">
  <h1><%= @category.name %></h1>
  <!-- Mobile view -->
  <% if @products.present? %>
  <% if browser.mobile? %>
    <% @products.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.compact.each do |product| %>
              <div class="col-sm-12 col-md-4">
                <div class="tile-offset" style="background-image:url('<%= product.image_1 %>');">
                  <a href="<%= url_for(action:'show', controller:'products', id:product.id) %>">
                  <div class="product-overlay HIDE">
                    <div class="title">
                      <h3 style="padding-top: 50%;"><%= product.name %></h3>
                    </div>
                    <div class="bottom" style="background-image:url(http://i.imgur.com/6HsvJeM.png), url(http://i.imgur.com/IPQHutD.png);background-size:50%,51%;background-position:left,right;background-repeat:no-repeat;">
                      <div class="bottom-left">
                        <h6>AS LOW AS</h6>
                        <h4>$<%= product.price %></h4>
                      </div>
                      <div class="bottom-right">
                        <h6>
                          <a style="color: white;" href="<%= url_for(action:'show', controller:'products', id:product.id) %>">
                          Quote
                        </a>
                      </h6>
                      </div>
                    </div>
                  </div>
                </a>
                </div>
                <% if admin_signed_in? %>
                  <%= link_to 'Show', [product.category, product], class: "btn btn-primary" %>&nbsp;
                  <%= link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-basecamp" %>&nbsp;
                  <%= link_to 'Destroy', [product.category, product], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                <% end %>
              </div>
        <% end %>
      </div>
    <% end %>
    <!-- end of mobile -->
    <% else %>
    <% @products.in_groups_of(3) do |group| %>
      <div class="row">
        <% group.compact.each do |product| %>
              <div class="col-sm-12 col-md-4">
                <div class="tile-offset" style="background-image:url('<%= product.image_1 %>');">
                  <div class="product-overlay HIDE modaling" href="#exampleModal<%= product.id %>">
                    <div class="title">
                      <h3><%= product.name.titleize %></h3>
                    </div>
                    <div class="bottom" style="background-image:url(http://i.imgur.com/6HsvJeM.png), url(http://i.imgur.com/IPQHutD.png);background-size:50%,51%;background-position:left,right;background-repeat:no-repeat;">
                      <div class="bottom-left">
                        <h6>AS LOW AS</h6>
                        <h4>$<%= product.price %></h4>
                      </div>
                      <div class="bottom-right">
                        <h6>Quote</h6>
                      </div>
                    </div>
                  </div>
                </div>
                <% if admin_signed_in? %>
                  <%= link_to 'Show', [product.category, product], class: "btn btn-primary" %>&nbsp;
                  <%= link_to 'Edit', edit_category_product_path(product.category, product), class: "btn btn-basecamp" %>&nbsp;
                  <%= link_to 'Destroy', [product.category, product], method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                <% end %>
              </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <% end %>


  <br>
  <% if admin_signed_in? %>
    <div class="pad-btm">
      <%= link_to 'New Product', new_category_product_path, class: "btn btn-basecamp" %>
    </div>
  <% end %>
</div>

<% if @products.present? %>
  <% @products.each do |product| %>
    <div class="modal fade" id="exampleModal<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title text-center" id="exampleModalLabel<%= product.id %>"><%= product.name.titleize %></h4>
          </div>
          <div class="modal-body">
            <%= render product %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Send message</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', category_products_path(@product.category) %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "product", locals: {product: @product} %>